### ISSUE TITLE
Updated Plugin no longer works...why?

### ISSUE THREAD

**Issue by putter10** [yikesinc/yikes-inc-easy-mailchimp-extender#109]
Plugin Version  5.0.4
Wordpress Version   3.9.2
Browser Information Google Chrome 36.0.1985.143 on Windows
Server Information  Apache

Please help me fix this!  Thanks!

**Comment by Valid** [comment]
Hey, hate to bring up this old issue, but many of my users encountered it today, and I cannot figure out what could have triggered it, other than _perhaps_ (though it would be odd) my list getting over 10k, because the problem seemed to have started right when that happened. I only noticed hours after it happened when I saw that sub rate was way lower than expected, and it was because people couldn't sign up, and were getting the 'Failed nonce security check.' error.

Any idea what might have happened? I'm interested because I don't want that to happen again. Today was one of my busiest days ever traffic-wise, and yet my lowest sub # for the week.

**Comment by clemsontiger** [comment]
Just got this security error as well. I reloaded the page and then it worked. I will note though that I was actively on a Sign up form edit page within mailchimp.com when I got this issue; not sure if it had anything to do with it, but thought I'd mention in case.

**Comment by TheTracyL** [comment]
I would recommend that everyone download and install the newest version of our plugin that we will be releasing very soon. In it we've resolved many reoccurring bugs. 

Download link: https://cloudup.com/files/iU2qFFvl2li/download

Upgrading to Version 6 articles: https://yikesinc.freshdesk.com/support/solutions/folders/6000128806

Using the new new version articles:
https://yikesinc.freshdesk.com/support/solutions/folders/6000131098

Thank you!
-Tracy
