### ISSUE TITLE
Issue with List Forms on WordPress MailChimp Plugin

### ISSUE THREAD

**Issue by brittneyburgett** [yikesinc/yikes-inc-easy-mailchimp-extender#142]
Hello,

The API for my mailchimp account is connected - it says so in my WP mailchimp settings, and I've tested the email subscription option on my blog. However, when I click on "Manage List Forms," I get a message that "You must enter a valid API key to import and manage your lists." I'm trying to update my list forms because I want to put a default that all sign ups here are from the Haven Life blog. Is that possible to do without having it featured in the list people need to fill out? Right now, we just have email address and zipcode. Will source need to be visible now also?

Please let me know.

Thanks,
Brittney

**Comment by ergh** [comment]
Hello:
Couple of questions on the Easy MailChimp Forms WP Plugin:
1. Can I make a Input field Read only? This is a hidden field, I just wanted to display the value
in the form (based on some other selection that user makes) and submit the form passing that
hidden input field.

2. I have single optin set up and a AR email series setup via Workflow in MChimp.
The 1st email is triggered immediately after subscription.
But the issue is, even if I turned OFF the "Final Welcome Email" in MC backend for this List, I still get that Welcome email then my 1st AR email from my 3 email series!
Is there somehow, this plugin is triggering that Default MC "Final Welcome Email" ?
How to stop that?

**Comment by EvanHerman** [comment]
@ergh if you have a question, please open a separate support ticket. This one will most likely be overlooked since it is marked as resolved.
