### ISSUE TITLE
Don't apply my API key.

### ISSUE THREAD

**Issue by PolGrey** [yikesinc/yikes-inc-easy-mailchimp-extender#178]
My Api key is ok and works great in other plugins, here i can't even press save button, its aways inscription in red that my api key invalid. What i need to do? Thanks

**Comment by Heatherhowdown** [comment]
I am also having this exact problem :(

**Comment by EvanHerman** [comment]
Hi Heatherowdown,

The issue seems to be related to the WYSIWYG editor on the settings page. Either another plugin you are running, or your theme is trying to load a custom button or some sort of custom functionality which is conflicting with either our plugin, or the default tinyMCE scripts.

The settings page should save via AJAX, which means the page should not have to reload after you hit 'Save'. If the page is reloading, this is most certainly indicative of a javascript error on the page.

If you'd like, you can email me at the email above and I'll go in and see what I can do about handling the error on the page.


Thanks,
Evan

**Comment by KraftsKISS** [comment]
I am having this same problem. It won't let me choose Save

**Comment by EvanHerman** [comment]
Please view what I have written above, and contact me if necessary.


Thanks,
Evan

**Comment by KraftsKISS** [comment]
So does that mean that I need to change my theme for this to work? Sorry I am new to all of this  


On Monday, January 5, 2015 3:05 PM, Evan Herman <notifications@github.com> wrote:
  


Closed #178.

**Comment by TheTracyL** [comment]
You can email Evan directly, evan@yikesinc.com, and he can investigate.

**Comment by ammarjutt** [comment]
Hello,
I am using mailchimp plugin but there is an issue with Api key when i enter it. Following Error is there.
"Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."
I have also check the consol option. there is an error
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

So please let me tell about the solution.. 

Thanks..!!!
