### ISSUE TITLE
MailChimp API key error and save button under settings disapeared

### ISSUE THREAD

**Issue by foerderadmin** [yikesinc/yikes-inc-easy-mailchimp-extender#192]
Hi,
suddenly my MailChimp Forms widget reports me "You must provide a MailChimp API key". It worked for now 4 month and suddenly it can´t find the key. And after I put it in again, it is checked as valid key, so I want to save the key again but there is no save button anymore.??? Can you help me, do you have any idea??

**Comment by EvanHerman** [comment]
Hi Foerderadmin,

It sounds like you recently installed a new plugin or switched themes and which cause a javascript error  to appear on your plugin settings page. I would recommend uninstalling any recently installed plugins that, or at least deactivating them temporarily to test which one may be causing the problem.


Thanks,
Evan

**Comment by MichaelScheffel** [comment]
I'm having a similar problem.  I installed Studio Press Genesis and News Pro theme.  Then I installed the mail chimp forms plug-in.  Even before I try to enter the mail chimp API, I am getting an error message, "invalid API key".  I paste it in anyway, error message remains and save key is grayed out.  I have deleted and reinstalled plug-In several times.  Is it not compatible with Genesis?

**Comment by EvanHerman** [comment]
I have not tested it with Genises, but I see no reason why it wouldn't be.

If you're getting an invalid api key error, but the save button is greyed out, can you head over to the debug settings page and try three things.

1) check the debug error log. That may tell you a better response form mailchimp.
2) toggle on ssl verify peer to false, and try your API key once more.
3) if all else fails, hit f12 on the settings page and check the 'console' tab for any javascript conflicts. If there is some sort of conflict with Genesis due to a js conflict, it will most likely tell us in the developer console.

Evan

**Comment by MichaelScheffel** [comment]
Don't know how or why, but hitting F12 fixed the problem.  Thank you.

**Comment by EvanHerman** [comment]
That is strange. Glad it's working now!
