### ISSUE TITLE
Mailchimp Form won't work via mobile.

### ISSUE THREAD

**Issue by lizhodgeart** [yikesinc/yikes-inc-easy-mailchimp-extender#194]
How can I make my newsletter mail chimp form work on my mobile phone?  www.lowcountrystreetgrocery.com

**Comment by EvanHerman** [comment]
Hi,

It looks like the styles are off on your site. The input fields and the signup button are not clickable, due to the container below it ( the Coming Soon widget ) overlaying on top of the sign up forms. This happens with your theme on any screen size below 992px.

The forms do work on Mobile, but as I've mentioned the widget below it is causing the fields to be un-clickable. You should try and adjust the styles so they overlaying on top of each other, then users will be able to submit the form.


Thanks,
Evan
