### ISSUE TITLE
It wont accept my mailchimp auth code

### ISSUE THREAD

**Issue by arnowsolutions** [yikesinc/yikes-inc-easy-mailchimp-extender#195]
i added my code in the wordpress plugin box but the submit button is not active.  How can i get pass this point to use the plugin?

**Comment by EvanHerman** [comment]
Hi If this is happening then it most likely means you have a javascript error on your page, either due to your theme or another plugin.

I would recommend disabling other plugins until you can locate the issue.

What have you tried to remedy the issue? As the plugin also suggest, I would check the debug log for any errors. Turn on advanced debug, etc.


Thanks,
Evan

**Comment by arnowsolutions** [comment]
Thanks! well it only says invalid API code but i did an exact copy and paste.

**Comment by EvanHerman** [comment]
Hi Arnowsolutions,

When you enter the API key, and it returns invalid, can you check the developer console for me.

Can you toggle on 'advanced error logging' on the debug tab, try entering your key and then checking the debug log again. It may return a separate error this time. If not...

Hit f12 on your keyboard, and click on the 'console' tab. This will tell us if there are currently any javascript errors, which would infact cause the API check to return invalid every time.


Thanks,
Evan
