### ISSUE TITLE
It won't accept my list

### ISSUE THREAD

**Issue by stephaniehester** [yikesinc/yikes-inc-easy-mailchimp-extender#197]
I am at a loss (this is all new to me.)  I have, obviously, downloaded the plugin.  I've entered my API code and it was verified.  When I select my list I see it on the drop down menu, but nothing happens.  I don't have an "update" button or anything to accept the list.  All I have is a "create a form for this list" button and that takes me back to the page that wants me to download the plugin again.  

I have a form created in my MailChimp account for this list so I'm not sure what I'm doing wrong.

Thank you for your help!

**Comment by EvanHerman** [comment]
Hi Stephanie,

It sounds like your having a javascript issue on the manage list forms page. This generally happens when other plugins or your theme is un-necessarily loading js files on our plugin page.

The only real way to diagnose the issue is to deactivate all plugins one at a time until the issue disappears. Then working backwards from there.

It's strange because your able to enter and save your api key, you shouldn't have an issue importing your list to the site.


Thanks,
Evan
