### ISSUE TITLE
Textarea, WYSIWYG, attachment fields

### ISSUE THREAD

**Issue by millerj** [yikesinc/yikes-inc-easy-mailchimp-extender#201]
Is it possible or is there any plan for the future to add options for textarea, wysiwyg editor, and attachment fields to the form?

**Comment by EvanHerman** [comment]
Hi Millerj,

We have considered adding text area fields to the plugin, but haven't had the chance to get around to it. MailChimp doesn't offer textarea fields in the forms, because MailChimp is intended to be used for opt-in to mailing lists as opposed to a contact form.

I'm not sure how the data would be handled on MailChimps part, other than the entire textarea field being sent in as a string to a store in standard text field on MailChimps server.

In terms of a wysiwyg, same idea but the HTML would all be stripped.

For file upload fields, it may be possible. At the moment we have support for an 'image' field which allows you to specify a URL to an external site. It would be hard to create an upload field, as the image would need to be uploaded to your site (for you to host it) then that url would have to passed to MailChimp. If you removed the image from your server, it would be inaccessible from MailChimp.



Evan
