### ISSUE TITLE
Updated plugin, not wokring since.

### ISSUE THREAD

**Issue by joeGimlik** [yikesinc/yikes-inc-easy-mailchimp-extender#204]
Since updating the plugin to 5.3.1 API key is not recognised. Forms have disappeared. Had to disable from site as all I can get in front end display is error message. API key is correct (is same one as before update).

When I added a new one... noticed no save button at bottom of settings page(?).

**Comment by EvanHerman** [comment]
Hi Joe,

What you describe sounds similar to either a TinyMCE error, or a javascript error. It sounds like you've either switched themes or installed a few new plugins which may be causing a conflict.

The TinyMCE error would occur if a plugin is trying to add custom buttons to the single and double opt-in message fields, unsuccessfully. If an error were caused by this, the Submit button is generally not present on the page.

I would recommend temporarily switching themes to see if that helps resolve the issue. That way we know it's theme related. If it's another plugin, it would be helpful to know what plugin it is and what is actually causing the problem. If we can pin point the plugin I can run some tests on my end.

Thanks,
Evan

**Comment by joeGimlik** [comment]
Hi Evan. Thanks for getting back so swiftly.

I haven't changed themes nor added any new plugins. Only change made has been to update the Mailchimp plugin. Perhaps the wp core needs to be up to date with 4.1 as well?

Excuse any typos, written on a "smart phone"

**Comment by EvanHerman** [comment]
Hi Joe,

If you want to email me at Evan@Yikesinc.com , I can personally take a look for you.


Thanks,
Evan

**Comment by EvanHerman** [comment]
If you're still having issues and need some help, please feel free to reach out at the email mentioned above.


Thanks,
Evan
