### ISSUE TITLE
API Key won't save

### ISSUE THREAD

**Issue by TTOCSports** [yikesinc/yikes-inc-easy-mailchimp-extender#225]
Hello,
I am very new to this and I am having a problem with the API key where I am trying to connect my Mail Chimp account to WordPress.  I have copied the API from my account on the website, but when I enter it I cannot click on "Save Settings" to save it - the only clickable option is Reset Plugin Settings.

Thank you!

Jennifer

**Comment by EvanHerman** [comment]
Hi Jennifer,

I've removed your screenshots as they contained your API key which grants near full access to your MailChimp account.

Are you able to check the error log on the debug tab from the settings page? You can try toggling both of the settings and trying your API key again and re-checking the log for any new errors that will help pin point the issue.

Evan

**Comment by EvanHerman** [comment]
Hi,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
