### ISSUE TITLE
Interest Group Check box not functioning

### ISSUE THREAD

**Issue by knighttan** [yikesinc/yikes-inc-easy-mailchimp-extender#232]
Hi,

I created interest group within a list in MailChimp. But the checkboxes do not function in the form page which I created in wordpress using easy mailchimp extender. 

![image](https://cloud.githubusercontent.com/assets/11580917/6763447/56d7a4be-cfb8-11e4-9974-6c126cf894ed.png)

In the Error Log, it shows this

![image](https://cloud.githubusercontent.com/assets/11580917/6763448/60741e58-cfb8-11e4-86aa-45be5a59135f.png)

I looked into any setting in MailChimp, I cannot find a place to enable or disable the interest group fields. In MailChimp, the interest group field is set to visible. 

Anyone could help? Please...

**Comment by EvanHerman** [comment]
Hi Knighttan,

Did you create the interest groups from within the plugin, or over on MailChimps side? You may want to try and re-import your list back into the plugin. Some of the data associated with the form could have gotten jumbled.


Evan

**Comment by EvanHerman** [comment]
Hi,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
