### ISSUE TITLE
won't accept api code

### ISSUE THREAD

**Issue by 2Rabbits** [yikesinc/yikes-inc-easy-mailchimp-extender#234]
Hi there!

I'm getting a "Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information." by default. It won't accept the actual code. Error log lists "invalid MailChimp API Key" but doesn't record a correct date with that.

**Comment by EvanHerman** [comment]
Hi 2Rabbits,

You may have a JavaScript error on the page, which is preventing the ajax function from firing correctly. If you'd like, you can email me at Evan@Yikesinc.com and I'll get things squared away for you.

We're working on a complete re-write of the plugin to prevent this error from occurring in the future.


Evan

**Comment by EvanHerman** [comment]
Hi,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
