### ISSUE TITLE
API trouble

### ISSUE THREAD

**Issue by eliconan** [yikesinc/yikes-inc-easy-mailchimp-extender#235]
Hi there
I just activated the mail chimp form for wordpress but my API Key does not work, comes up this message ....Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information. I need help please

**Comment by EvanHerman** [comment]
Hi Eliconan,

Can you try generating a new API key and trying that one? You may not need to deactivate your old one first. Some users are able to successfully connect after generating a new icon.


Thanks,
Evan

**Comment by eliconan** [comment]
Hi thereThats what I did yesterday but it did not work, actually I created a third API Key today ,but I got the same message. What else can i do? Thanks. 


     El Viernes 27 de marzo de 2015 10:44, Evan Herman <notifications@github.com> escribió:
   

 Hi Eliconan,Can you try generating a new API key and trying that one? You may not need to deactivate your old one first. Some users are able to successfully connect after generating a new icon.Thanks,
Evan—

**Comment by EvanHerman** [comment]
If you'd like you can email me at evan@yikesinc.com and I can take a look for you. I'll need you to email me temporary admin account along with your API key.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
