### ISSUE TITLE
API Key Invalid

### ISSUE THREAD

**Issue by cbinion73** [yikesinc/yikes-inc-easy-mailchimp-extender#237]
I have tried uninstalling and reinstalling the plugin and creating a couple new API keys. I am using the premium version of GeneratePress.  When I enter the API key it still says invalid.

**Comment by EvanHerman** [comment]
Hi Cbinion73,

It sounds like some sort of JS error on the page, or another reason outside the scope of our plugin. We're currently in the midst of re-writing the entire plugin to prevent this issue from happening moving forward. We're currently in an [alpha stage](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging). When that's release, users should no longer run into this annoying issue.

If you'd like to email me at Evan@yikesinc.com I can take a look at what the issue may be.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
