### ISSUE TITLE
Cannot save Form Options on Wordpress

### ISSUE THREAD

**Issue by fooduzzi** [yikesinc/yikes-inc-easy-mailchimp-extender#238]
Hi,

I am trying to set up my subscription preferences, but there is no option to save on the Form Options tab. Every time I leave that tab, all of my changes have gone unchanged. I am trying to add my API Key (which it validates) and change my Success Message.

Am I missing something?

Thank you.

**Comment by EvanHerman** [comment]
Hi,

it sounds like you have a JavaScript error on the page thus causing the save button to not render. You'll need to make sure your theme and any other plugins you have running aren't causing errors otherwise the forms won't function at all.

If you want to email me at Evan@yikesinc.com I can take a look for you if you're unsure how to check.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Dean,

You might want to give our latest release a shot. It's currently sitting in the staging repo as a beta. We'll be cleaning up a few things, adding some more documentation and maybe a few more filters and hooks before we actually push this out to the repository. This is a complete re-write of the entire plugin. We did this to squash these bugs that keep popping up. Please give it a shot and let me know if the issue is gone.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan
