### ISSUE TITLE
Required radio option leads to javascript error

### ISSUE THREAD

**Issue by rolfkleef** [yikesinc/yikes-inc-easy-mailchimp-extender#241]
Hi, I'm running into a problem with forms with a radio options field.

The first list of options on http://kvzeeburg.nl/aanmelden-voor-clinic/ should be required, but when marked so, the form doesn't submit and results in a javascript error "TypeError: $ is not a function" in this extra bit of code in the page (specifically: the else branch below):

```javascript
if($ymce('.8113d7c747CLINIC:checked').length <= 0) { 
	msg += '<li>Ik wil meedoen aan de volgende clinic\n</li>';
	err++;
	$('label[for=1-8113d7c747-clinic]').next().find('input').addClass('yks_error_field_required shake animated').delay(800).queue(function(next){
		$(this).removeClass('shake animated');
		next();
	});
} else {
	$('#1-8113d7c747-clinic').removeClass('yks_error_field_required')
}
```

On first sight looking at the page code, it appears everywhere else $ymce() is used instead of $()?

**Comment by EvanHerman** [comment]
Hi Rolfkleef,

Thank you for bringing this issue to our attention. This isssue will be fixed in the new version of the plugin. We didn't want to go back and fix any issues in the current version as our [new version](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging) is going to be a major upgrade to the current infrastructure.

Thanks,
Evan
