### ISSUE TITLE
Interests Group data not captured

### ISSUE THREAD

**Issue by dion1231** [yikesinc/yikes-inc-easy-mailchimp-extender#244]
Hi, I'm having issues with the form capturing interest group data.  I have a series of checkboxes and it doesn't not seem to capture the data when I go to look at the record on Mailchimps site list. I have removed the form in the Manage List Forms backend and also re-imported form fields again and still doesn't work. Any ideas?

I'm running:
Plugin Version	5.4.3
Wordpress Version	4.0.1

**Comment by EvanHerman** [comment]
Hi Dion,

A few of our other users have reported this issue. We're working on re-writing the entire plugin from the ground up to help avoid many bugs that have been reported lately. A lof of the errors are caused by js issues due to the heavy use of AJAX throughout the plugin, but the interest group issue doesn't seem to be related.

Its possible the issue lies in the way the interest group array is being constructed and passed to MailChimp.

If you take a look at the filters and hooks we've provided, you'll notice one useful helper function called `dump_user_data_from_form();`.

If you implement this function, you'll get a chance to see what data is actually being sent over to MailChimp, including the interest group array.

If you can get a dump of that, it should be a good indicator of whats going on there. Just copy the function we've provided in the readme to your functions.php and try submitting a form as a test to see the returned data.

```php
<?php
    /**
    * This example will dump all of the submitted 
    * user data, so you can see the full array of data
    * being returned
    */
    function dump_user_data_from_form( $form_ID, $merge_variables ) {
        if( class_exists( 'yksemeBase' ) ) {
            $yikes_easy_mailchimp = new yksemeBase();
        }
        $yikes_easy_mailchimp->yks_mc_dump_user_data( $form_ID, $merge_variables );
    }
    add_filter( 'yikes_mc_get_form_data' , 'dump_user_data_from_form', 10, 2 );
?>
```


Evan

**Comment by dion1231** [comment]
Thanks for the quick and helpful response Evan.

This is what I get when I insert the 2nd function into my theme's function.php file
![screen shot 2015-04-08 at 10 22 52 am](https://cloud.githubusercontent.com/assets/11842546/7047265/75805ee0-ddd9-11e4-812d-145544b36326.jpg)

**Comment by dion1231** [comment]
Haven't heard in awhile....any ideas??

**Comment by EvanHerman** [comment]
Hi Dion,

Unfortunately no, I have not had a chance to look into the issue. I am currently in the midst of re-writing the entire plugin. There will not be any more updates to the current version moving forward.

If you want to email me at Evan@Yikesinc.com I can take a look for you personally, but I will need to have access via FTP to make any necessary adjustments to the plugins code base.

Other than that my recommendation is to wait for the re-write and or the premium version to be released. We are working diligently to iron out any bugs in the current version before releasing a new version.

If you're getting an undefined variable error, than it simply means that your merge variables aren't being sent properly and probably what is causing the issue for you on your site.


Evan

**Comment by dion1231** [comment]
Ok, thanks for the reply. I will have to wait then.
