### ISSUE TITLE
PHP Notice:  Undefined index: yks_mc_chimp_chatter_heartbeat

### ISSUE THREAD

**Issue by plesiosaure** [yikesinc/yikes-inc-easy-mailchimp-extender#246]
This occurs in yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php on line 3787

**Comment by EvanHerman** [comment]
Hi @plesiosaure,

We've since re-written the entire plugin from the ground up and stripped out the heartbeat functionality from our plugin. This seemed to cause some confusion for a few users (and a few issues).

You may want to give our latest release a try.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

We have ironed out many of the bugs outlined mentioned here on GitHub.

Thanks,
Evan
