### ISSUE TITLE
Error message: this form doesnt exist...

### ISSUE THREAD

**Issue by acannon17** [yikesinc/yikes-inc-easy-mailchimp-extender#258]
I've got my API connected and can see my lists in the drop down but when I click Create to create a new form I get the error message: Whoops! It looks like this form doesnt exist...

We've already installed the latest release: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Please help

**Comment by EvanHerman** [comment]
What does your shortcode look like?

**Comment by acannon17** [comment]
Here is what my IT guy did/replied:

I deactivated it, deleted it, went through the database to try and remove all the stuff it left behind, and then reinstalled, and am getting this:
======================
"It looks like you're upgrading from a previous version of YIKES Inc. Easy MailChimp Extender. In the latest version YIKES Inc. Easy MailChimp Extender, the options data structure has changed. We'eve also moved lists into its own database table to allow for some higher level customization. Now you can easily create multiple forms and assign them to the same mailing list.

Before you continue, its strongly recommended you the perform the migration to ensure the plugin continues to function properly.

<Perform Migration>"
=====================
But there shouldn't be anything to migrate. And if I click <Perform Migration>, it goes through some steps and comes back to the same screen again.

Wondering if this plugin works with Multisite? Or how I can eradicate it so I can try a completely fresh install?

**Comment by EvanHerman** [comment]
I'm not entirely sure whats going on...

If you previously had our other MailChimp plugin installed then you're going to get that message to migrate the options. That's why.

Are you getting any other messages such as the table doesn't exist in the database? Can you grant me temporary access so I can take a look. I am a bit confused on what you've done/tried to resolve the issue.

You can email me at Evan@yikesinc.com

Thanks,
Evan
