### ISSUE TITLE
Can not find ykfmc-submit in the CSS file

### ISSUE THREAD

**Issue by rookieminds** [yikesinc/yikes-inc-easy-mailchimp-extender#259]
Hi I m a developer and I just started working with Wordpress
I did install mail chimp plugin and everything s good
But I need to have more customization on the preview of the form 
I checked all the css files inside the css folder in /wp-content/plugins/yikes-inc-easy-mailchimp-extender/css but could n find any related class for my lable and submit button 
Would u plz tell me where i can find access to my css attributes
where can I see ykfmc-submit class?
Regards

**Comment by EvanHerman** [comment]
I'm confused as to what your trying to achieve. Why do you need to locate the styles for the submit button?

If I remember correctly the styles are all declared by your theme and not declared in the plugin style sheet. You also shouldn't be making changes to our style sheet because in the next few days when we update the plugin all of your changes will be reverted to it's original state. You may want to look into creating a child theme.

**Comment by rookieminds** [comment]
Hi 
what i mean is I need to restyle the actual Form to my favorite style 
The actual form is like this:

![1](https://cloud.githubusercontent.com/assets/12181942/7424840/409e1c08-efea-11e4-88c0-7508f46272f3.png)

And I want to change it to this
![2](https://cloud.githubusercontent.com/assets/12181942/7424845/509f1b66-efea-11e4-8d03-4ace4cfddc06.png)

So I think I shoud change the CSS of the plugin 
Am I right?

**Comment by TheTracyL** [comment]
No, you would actually style all elements of your site with the Theme's CSS file(s) or a child theme CSS file. 

You don't want to touch plugin files, because they will be wiped out with updates. We provide classes on all form elements so you can style them with a theme's CSS

**Comment by TheTracyL** [comment]
Here is the Codex article on Child Themes:
https://codex.wordpress.org/Child_Themes

Once you have it set up you can use style.css to add your own styles to make the form look however you want.
