### ISSUE TITLE
Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.

### ISSUE THREAD

**Issue by cuteedge** [yikesinc/yikes-inc-easy-mailchimp-extender#269]
when i tried to integrate the form with mailchimp API KEY, the error message was permanently there: Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.

**Comment by EvanHerman** [comment]
Hi Cuteedge,

There seems to be an issue for some of our users with the old version. I would recommend downloading the latest beta release that we've been working diligently on. The issue seems to be suppressed in the new release. 

If you head to the [staging repo](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging), and scroll down a little bit you'll see a link to download the latest stable release. I would recommend downloading and installing that version, you should have no issues connecting to the MailChimp API.


Thanks,
Evan

**Comment by cuteedge** [comment]
Thanks, now i have connected but the form is displaying with an error in RED that says:ERROR: Invalid domain for site key
  


     On Monday, May 18, 2015 2:03 PM, Evan Herman <notifications@github.com> wrote:
   

 Hi Cuteedge,There seems to be an issue for some of our users with the old version. I would recommend downloading the latest beta release that we've been working diligently on. The issue seems to be suppressed in the new release. If you head to the staging repo, and scroll down a little bit you'll see a link to download the latest stable release. I would recommend downloading and installing that version, you should have no issues connecting to the MailChimp API.Thanks,
Evan—

**Comment by EvanHerman** [comment]
Hi,

I have not encountered that error before. Where is that error being displayed? Do you have a link to the page?

Thanks,
Evan

**Comment by cuteedge** [comment]
Yes http://marriageisnow.com/
  


     On Monday, May 18, 2015 9:07 PM, Evan Herman <notifications@github.com> wrote:
   

 Hi,I have not encountered that error before. Where is that error being displayed? Do you have a link to the page?Thanks,
Evan—

**Comment by EvanHerman** [comment]
That error is because you have the recaptcha setting enabled.

You'll want to head into 'Easy MailChimp > Settings' and in the right hand sidebar select 'ReCaptcha'. Either disable the feature or add an appropriate API key that is assigned to that site. 

That will get the issue cleared up for you.


Evan

**Comment by EvanHerman** [comment]
I am closing this thread due to inactivity. If you need additional assistance feel free to comment here.

Thanks,
Evan
