### ISSUE TITLE
new text box gets error

### ISSUE THREAD

**Issue by rupwood** [yikesinc/yikes-inc-easy-mailchimp-extender#272]
I get an error message when I try to add a new text box. Also, I don't see where I download boilerplate templates. It's not on the manage list forms page

**Comment by EvanHerman** [comment]
It sounds like you're using our old version, which is no longer supported.

I would recommend you use the latest stable release. We have since removed the templating system from the plugin in anticipation of moving it into a premium add-on.

https://cloudup.com/cBKo-0D2HTV

Thanks,
Evan

**Comment by rupwood** [comment]
I just installed the version you sent and it is even harder to navigate than the other. Where's the recapcha and the advanced style options? Is it supposed to be working with the older version? I deleted the first version. I still don't see where to download boilerplate templates???

**Comment by EvanHerman** [comment]
Hi,

As mentioned in the previous post our tempting system has been taken out of the core plugin as we plan to release it as an add-on to the main plugin base. We are planning to do the same for our form customizer. Those sections are rather large, and not ever user takes advantage of them so we've decided it'st best to move them to an add-on.

In regards to recaptcha, you'll find that inside of the Settings page. You'll find the link to the reCaptcha page inside of the sidebar in the right hand sidebar menu.

Thanks,
Evan

**Comment by rupwood** [comment]
Thanks for getting back to me. How would I change the width of the form then?

**Comment by EvanHerman** [comment]
You can adjust the width of the form using CSS.

```CSS
.yikes-easy-mc-form {
   width: 50%;
}
```

You'll want to make sure that you're overriding the default 100% width of the forms declared in our stylesheet. If you can't figure that out, simply add an !important tag to the code above to get things working.


Thanks,
Evan

**Comment by rupwood** [comment]
Hello Evan,

Thank you, this worked. Now there is another problem, the last name text box is gone and it won't let me add a new text box. In fact if I try to edit any of the text boxes it gets an error message. I understand that you want people to go pro but $50 seems high especially when things that are supposed to work don't…

Linda

**Comment by EvanHerman** [comment]
Hi Linda,

What sort of errors are you seeing when adding fields to the form? This release is still in beta, we have not released it yet so we can have a chance to iron out bugs, write documentation etc.

It sounds to me like you're getting some sort of JavaScript error on the page, which could be due to a conflict with another plugin and not necessarily our plugin.

If you would be willing to email me at Evan@Yikesinc.com with some temporary credentials I would be more than happy to take a look into the issue you are facing, because I have not had other users report an issue when adding fields to a form.


Thanks,
Evan
