### ISSUE TITLE
Pre-select interest group items

### ISSUE THREAD

**Issue by amikostudio** [yikesinc/yikes-inc-easy-mailchimp-extender#279]
Hello,

I was wondering whether this feature is included, can be included, or can be implemented from my end via the code if the first two don't apply? It doesn't necessarily break the plugin -- not being able to pre-select a group -- though I feel having the option to pre-select from within the plugin settings would be a very helpful feature. 

Sorry if this is posted in the wrong spot!

Many thanks,
Al

**Comment by EvanHerman** [comment]
Hi Al,

In the current version I don't believe that it is easily possible. In the upcoming release of the plugin we've enabled this feature.

If you'd like, feel free to give our latest stable release a shot. We're currently in beta testing, and would love to hear some feedback. You can find the download link in the readme file on the staging repo: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Or you can download it directly from https://cldup.com/TXlbe0izFH.zip .


Thanks,
Evan

**Comment by amikostudio** [comment]
Thanks for the reply Evan.

Just to confirm, the version you sent through does, do doesn't contain the
functionality to force/preselect a group selection?

What are the main additions in the version you sent through, and when will
the upcoming release be released?


Thanks again,

IT Support // Amiko Studio
*Amiko Studio* <http://amikostudio.com.au/>
0413 963 514

**Comment by EvanHerman** [comment]
Hi,

In that version, yes you can pre-select interest group options. The entire plugin has been re-written from the ground up and some of the features have been removed and moved into separate extensions for the base plugin.

Some of the features weren't being utilized by our users so we decided instead of bloating the plugin with features, we'd break things off into extensions so users can pick and choose what they need. The new version is far more stable and extensible than the previous version.

We are aiming for an end of July release with the base plugin being rolled out to the repository and at least 3 extensions built out and prepped for launch.

Thanks,
Evan
