### ISSUE TITLE
Apostrophe error

### ISSUE THREAD

**Issue by rolfkleef** [yikesinc/yikes-inc-easy-mailchimp-extender#296]
I added a list field that includes an apostrophe: Aantal open kano's

In version 5.4.3, this results in a javascript error in the page: the apostrophe doesn't seem to be escaped:

```
msg += '<li>Aantal open kano's'+'\n</li>';
```

Hopefully fixed in the upcoming new release, but I wanted to flag this as a possible test case :-) (maybe related to #202)

**Comment by EvanHerman** [comment]
Hi Rolfkleef,

The ticket you referenced was for the latest verison that we have up here in the staging repo. That will be rolled out to the WordPress repository as we comb through the bugs and finalize things

The apostraphe error you mention has been fixed in the upcoming release. Feel free to download it from the staging repo, or hold off until it hits the repo.


Thanks,
Evan
