### ISSUE TITLE
 API call to helper/ping failed: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [yikesinc/yikes-inc-easy-mailchimp-extender#306]
Hello, just tried the new version of the plugin (rc3) for the first time anywhere in local host and get:

'API call to helper/ping failed: SSL certificate problem: unable to get local issuer certificate'

I can't enter my MailChimp API Key.

**Comment by EvanHerman** [comment]
Hi,

This is a known error on localhost when trying to connect with MailChimp API. I would recommend following the steps outlined in this article:
http://redwebturtle.blogspot.com/2013/09/mailchimp-api-v20-ssl-error-solution.html

I have used the steps in the article above on numerous occasions.

If you need some help feel free to comment here and I'll see what I can do.


Thanks,
Evan

**Comment by Learn-Digital-Audio** [comment]
Thanks, but I am not an advanced programmer. This is too complex for my simple brain :) Your old version of the plugin didn't have this problem for me, and i remember it had a workaround built in for local host use? 

Is a fix possible on your end?

**Comment by EvanHerman** [comment]
No , there is no possible fix on our end. This is a limitation of localhost. You don't have the proper certificate files installed, so you're not able to properly connect to the API. We included some toggle on the settings page in our old version, but going that route forced the API connection not to be validated which is a security issue (which is why we've excluded it from the latest release). We didn't want to add un-necessary code and builk to the plugin, especially if it's the incorrect way to handle things.

You shouldn't have this issue on a live server, only on local host. This is an issue across numerous API's when on localhost.. The second work around in the link I've provided above is not a difficult fix. It requires changing one line inside of the MailChimp API code. This is how we built in a work around in our old version.

You'll need to open the following folder:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/includes/MailChimp/Mailchimp.php#L153

You can try adding the following code:
` curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, false);`

If that doesn't work you'll have to go through the steps outlined in the first resolution. There is no other work around for localhost installs, this has been an issue with the MailChimp API for sometime.



Evan

**Comment by Learn-Digital-Audio** [comment]
Thanks for your help. I tried your first suggestion and it did not work. I have gone back to the old version.

I suggest you warn people about this before the update as it's a bit of a show stopper. Thanks again for a great free plugin. I hope it can get resolved by the guys at mail chimp one day!

**Comment by EvanHerman** [comment]
Thanks for the input. There is not much to warn about. Within our readme we've provided a link to that article so users can work around the issue. Within the plugin itself we've also provided a notice alerting the user of such a conflict. Unfortunately, as previously mentioned, it's not something that we can handle on our end as it is directly related to your local install.

Thanks,
Evan
