### ISSUE TITLE
Access Control error - Easy Mailchimp and WPML

### ISSUE THREAD

**Issue by kristinGudmunds** [yikesinc/yikes-inc-easy-mailchimp-extender#321]
Hi
I hope I can explain my issue so that you'll understand ( I have no idea what is happening :) ):

I have a wordPress install where I use WPML language plugin to manage the two languages I have: they are english and icelandic.

In WPML I have the option to add a custom domain for each of the language, which I have done for the icelandic part. So, the site on english (which is the default language and the domain the wp install is installed on) is fjarhusidyarnstore.com. The icelandic domain is: fjarhusidgarnverslun.is and it is pointed (with some sort of a server alias thingy) at my wp install.

The error I get is this one:

XMLHttpRequest cannot load http://fjarhusidyarnstore.com/wp-admin/admin-ajax.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fjarhusidgarnverslun.is' is therefore not allowed access.

I get the error here: http://fjarhusidgarnverslun.is/umsokn/  (and in the form in sidebar, guessing this is because these are on the .is domain?)

It is preventing Easy Mailchimp to work as it is supposed to, that is, it sends all the information and stuff, the only thing missing is that it wont redirect to the page I had chosen or if I have no page chosen, it wont display "thank you for subscribing". I have googled around and understand that it is because of a script error of some sort.

I do not get an error here: http://fjarhusidyarnstore.com/making-a-gauge-swatch/ if I use the subscribe form in sidebar.

Do you think there could be a solution for this?

**Comment by EvanHerman** [comment]
Hi,

Are you using the current version from up in the WordPress repository or have you tried downloading the latest stable beta release from the staging repository?

Since the form is submitting via ajax the data needs to be sent and received on the same domain. It cannot be sent across domains for security reasons.

Are these two sites on a multi-site install? I would recommend trying to install the latest stable beta from the staging repo as it is multi-site ready.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Evan

**Comment by TheTracyL** [comment]
Hi I am closing this since we haven't heard a response.
