### ISSUE TITLE
Problem with using Chinese characters from an interest group's value in signup forms

### ISSUE THREAD

**Issue by rija** [yikesinc/yikes-inc-easy-mailchimp-extender#345]
Hi,

I have a Mailchimp list with an interest group called PREFERRED LANGUAGE FOR COMMUNICATION with two possible values:
* English 
* 繁體中文

When I add the interest group in the form builder, the two radio boxes labels appear correctly and after clicking on "Update form" and view the web page with the embedded form, both radio boxes are shown correctly (for label and value).

However if I go back to the form builder, open the form and the tab for the interest group
the second radio box for Chinese language appears as 'U7E41U9AD4U4E2DU6587'.
If I click on 'Update form' with that state and view the web page with the embedded form, the second option is shown in the web browser for both label and value as  'U7E41U9AD4U4E2DU6587'   

So whenever I need to make a change to the form,  I have to remove the interest group field from the form builder and re-add it again to preserve the integrity of the radio boxes.

I use the version of the plugin mentioned in the last comment of  #334

**Comment by EvanHerman** [comment]
Hi Rija,

Thank you for reporting the issue here. I am going through and writing out the documentation and ironing out any bugs before releasing things. I will have a look into the reported issue, see if I can replicate it and if need be push out an update to resolve things. This issue will most likely be resolved before release, as all characters should be accepted.

Thanks,
Evan

**Comment by rija** [comment]
Thanks for looking into it. 
I forgot mention that I'm seeing this behaviour on latest version of Safari  and Firefox 38

**Comment by EvanHerman** [comment]
Hi Rija,

I just went in and took a look and did run into the issue as well. I've since gone ahead and patched things up, and pushed out a new update to resolve some other issues, adjust a few styles and resolve the issue that you had mentioned above.

Feel free to download the latest release candidate at the following URL:
https://cloudup.com/files/i0Y-cvGSuTl/download


If you are still having issues feel free to reach out and we'll take a look.



Thanks,
Evan
