### ISSUE TITLE
Failed nonce security check...

### ISSUE THREAD

**Issue by stephendanielkarpik** [yikesinc/yikes-inc-easy-mailchimp-extender#360]
multiple users are complaining that they receive the error below when trying to subscribe:

Failed nonce security check. Please reload page and submit this form again.

http://discovercompass.org/school/carbondale-community-school/ccs-7-8-learning-center/

**Comment by EvanHerman** [comment]
Hi,

I just attempted to subscribe via the page provided above and had no issues. The submission went through without issue.

As a reference, you may want to take a look at the following threads:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues?q=is%3Aissue+nonce+is%3Aclosed

In short, the issue is most likely related to a caching plugin that you have running on the site.

I would recommend giving our latest version a try, which is a complete re-write of the version you currently have installed.

You can download it from the following URL:
https://cloudup.com/files/igb9MJNZhKd/download


I would first recommend trying to resolve the nonce security issue.



Evan

**Comment by stephendanielkarpik** [comment]
thx!

i think you're right, i had WP Fastest Cache installed but just this
morning switched over a VPS and removed that plugin... it seems to be
working again.

**Comment by TheTracyL** [comment]
Great!
