### ISSUE TITLE
Submit Button Inoperant

### ISSUE THREAD

**Issue by enxaqueca** [yikesinc/yikes-inc-easy-mailchimp-extender#369]
Clicking on Submit won't have any effect in http://www.alexandrefeldman.com.br/newsletter/ .

I was unable to diagnose any JavaScript errors.

**Comment by EvanHerman** [comment]
Hi Enxaqueca,

After taking a look it looks like you have a field for a URL title 'FB', which is currently set to be hidden. Since it's a URL field, it needs to have a valid URL in it for it for the form to submit successfully.

If you un-hide it and enter a URL you'll see the form works as intended. I'm not sure if you meant to have that field hidden or not. If you meant for it to be hidden, you can use one of the pre-defined tags to pre-populate it with a valid URL or use the value field to pre-populate it with a set URL.


Evan

**Comment by enxaqueca** [comment]
Hi Evan,

The reason I've hidden that field is that even though it had been set as optional (not required), a pop-up message would appear on Submit, prompting to please enter a valid URL. As a workaround for this issue, I hid the 'FB' field. I have unhidden it now - and even when I fill it with a valid URL, this dreaded message appears after Submit: "Whoops, something went wrong! Please try again."

**Comment by EvanHerman** [comment]
I just tested the field with the FB field not-hidden, and it seemed to go through for me. Since the field is a URL field it requires a valid URL to be input before the form can be submit. Since you set it to optional, you can remove the http:// that is set there on initial load, and you should then be able to submit the form.


Evan

**Comment by enxaqueca** [comment]
Evan, I keep getting the same issue. Are you sure you tested the submit in www.alexandrefeldman.com.br/newsletter/ and not the URL of the other issue that I had reported and is working since?

**Comment by EvanHerman** [comment]
Hi, yes I just re-tested with the URL mentioned above. Things went through without any issues.I see you removed the http:// from the URL field.

You might want to try clearing your browser cache. Sometimes things glitch a bit. Also if you've changed anything on MailChimps side, you may want to try clearing the API cache in 'Easy Forms > Settings > API Cache'.


Evan

**Comment by EvanHerman** [comment]
Correction - I just cleared my cache and the error is now there.

I'll try and see if I can figure out what might be going on. I would recommend trying to toggle on advanced debugging in the meantime.

Evan

**Comment by enxaqueca** [comment]
Meanwhile, in case I decided to get rid of that 'FB' field, how would I be able to do so? I can't seem to find a way to remove a field from the Form Builder.

**Comment by TheTracyL** [comment]
I got the error in Firefox, but it worked in Chrome. We'll try to get to the bottom of it. 

![success](https://cloud.githubusercontent.com/assets/1252286/10264959/42bcfd1c-69eb-11e5-83dd-1f8d70a2208a.png)

**Comment by TheTracyL** [comment]
If you expand a field, there is a Remove Field link. 

Please check out this KB article:
https://yikesinc.freshdesk.com/support/solutions/articles/6000030971-editing-forms

You'll see it in a screen shot towards the bottom.

**Comment by enxaqueca** [comment]
Thank you, Tracy.

**Comment by enxaqueca** [comment]
As soon as I enabled debugging, I have been able to send forms successfully. Is this expected to happen? No errors were logged while I had debugging enabled. I disabled it back - should I keep it enabled for a while longer?

**Comment by TheTracyL** [comment]
Hi Dr. Feldman.

Are things still working? If so I will close out this ticket.

Thank you!
-Tracy

**Comment by enxaqueca** [comment]
Hi Tracy,

Things are working, thank you. I enabled and disabled AJAX submission alone and in combination with Redirect on Submission, and all went smoothly. The only feature I haven't been able to implement without getting an error message was to hide the form after sign up in the test page www.enxaqueca.com.br/blog/easy-forms/ . I'll keep tinkering and let you know. Otherwise, the original issue can be closed.
