### ISSUE TITLE
Removing shortcut button from TinyMCE Editor Bar

### ISSUE THREAD

**Issue by manni65929** [yikesinc/yikes-inc-easy-mailchimp-extender#382]
I'd like to remove the shortcut button the form maker from the TinyMCE Toolbar, because only I, the admin should be able to add forms to a post. Is that possible?

**Comment by EvanHerman** [comment]
Hi Manni65929,

I am going to be pushing out an update later today, v6.0.2.4, which will will add a check for manage_options to the tinyMCE button.

I'll post back here when I get that version pushed out.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Manni65929,

I just pushed out a release which now wraps the tineMCE function inside of a check to ensure that only admins have access to the button.

If that ever needs to change you can use our built in filter `yikes-mailchimp-user-role-access` to change which capabilities have access to the major functionality of the plugin.

If things don't look right on your end feel free to re-open the issue here and we can discuss. Otherwise, if you're enjoying the plugin we would love it if you could leave us a nice review in the repository: https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

Thanks again!
Evan
