### ISSUE TITLE
problem when validating API key with mailchimp

### ISSUE THREAD

**Issue by baxivanos** [yikesinc/yikes-inc-easy-mailchimp-extender#386]
hi getting this message when trying to connect to mailchimp thru the plugin.

 API call to helper/ping failed: SSL certificate problem: unable to get local issuer certificate

is this a known problem ?? this worked perfect on 2 out of 3 sites i have 

Andreas

**Comment by EvanHerman** [comment]
Hi Andreas,

This is a known issue and something that lies at the server level and not with the plugin itself. A quick Google search will bring up a number of users reporting similar issues. What I can recommend is you take a look at the following article : http://redwebturtle.blogspot.nl/2013/09/mailchimp-api-v20-ssl-error-solution.html

I have only ever run into the issue on a localhost installation and was able to work around it using soution 2 found in the article above.

Who is your host and can you provide us with some additional server details? What OS is your server running on?


Thanks,
Evan

**Comment by baxivanos** [comment]
hi 
ok great will take a look at it, actually I have two sites on the same host provider that has the same setup one is working and the other one is not working..

I can give you temporary access but connect with me at Skype,, will send you details offline.. would like to solve this issue as it is a great tool and I want to use it on all my sites in the future..

best

Andreas

**Comment by gitJMDR** [comment]
I'm having this issue too, but only have access to the WP installation admin and FTP folder, not the server. Is it possible to correct the issue from there?

**Comment by EvanHerman** [comment]
Unfortunately, no it's not possible. You have to have access to server files.

**Comment by gitJMDR** [comment]
Okay, thanks—I'll get in touch with the admin

**Comment by EvanHerman** [comment]
After doing a big more research the best peice of advice that I found was to : 

Contact hosting company and request assistance; i.e., ask them to update the certificate bundle that your installation of WordPress uses.

If you would like to read more about the issue and why it may be occuring, you can find a great article here: https://s2member.com/kb-article/ssl-certificate-problem-unable-to-get-local-issuer-certificate/

Check under: "Why does https:// (SSL) communication fail?" and follow the instructions for step 2.

- Contact hosting company and request assistance; i.e., ask them to update the certificate bundle that your installation of WordPress uses.
- Or, (NOT recommended, due to security issues) disable SSL verification for remote sites; i.e., trust they are secure. This is accomplished by creating the following file in your installation of WordPress.

Create this directory and file: /wp-content/mu-plugins/ssl-no-verify.php
```
add_filter('https_ssl_verify', '__return_false');
```




Evan

**Comment by gitJMDR** [comment]
Awesome, thanks for looking into this.

—Jonathan

**Comment by baxivanos** [comment]
will test and see if it works,, the first one dident work solution nr2

**Comment by EvanHerman** [comment]
We have now created a knowledge base article to help out with the process of debugging this error:

https://yikesplugins.com/support/knowledge-base/i-receive-the-error-ssl-certificate-problem-unable-to-get-local-issuer-certificate-why/


Evan

**Comment by baxivanos** [comment]
it is the same solution Functions.php to add the line,, no file in MU_pligins ?

**Comment by EvanHerman** [comment]
Which link are you referring to?

You don't need to add it as an MU to my knowledge.

**Comment by baxivanos** [comment]
ok,, I tested the recommendation in KB but dident work,, I don't know if it takes a while before it might work or if I need to restart the plugin

**Comment by EvanHerman** [comment]
If that didn't work your best bet is to contact your host provider as step 1 suggests. A quality host should know how to handle the issue at hand.


Evan
