### ISSUE TITLE
Form Table Missing

### ISSUE THREAD

**Issue by NicoleDelacroix** [yikesinc/yikes-inc-easy-mailchimp-extender#388]
I've uninstalled and reinstalled, deactivated and reactivated, added my API key several times and no matter what I do, I keep getting the following message:

It looks like the forms table is missing. Please de-activate and re-activate the plugin to attempt to create the table. If the error persists, please get in touch with the YIKES Inc. support team.

I'm using the X theme, and this is an add-on through the theme (I've even uninstalled and reinstalled through my theme to no avail).  Is there anything I can do at this point to get it working?  Should I try a new API key?  Am I missing something? 

Thanks in advance for any help.

**Comment by EvanHerman** [comment]
Hi Nicole,

When the plugin is activated, the plugin will generate a table in the database that will house all of your form data. If there is some sort of issue during activation, and the form table doesn't get created - the plugin should display an error.

If you're seeing that error message it generally means that there was an issue during activation and the plugin was unable to create the table inside of your databse.

Are you activating the plugin as an admin? Is this a standard wp install or multi-site? Is it a live site or localhost install? What hose are you currently using?

Do you have access to cpanel or phpmyadmin of your hosting environment?


Thanks,
Evan

**Comment by NicoleDelacroix** [comment]
Hi Evan!

First, thank you for the quick response. I'm using a standard wp install on a single site, and yes, it's live. I use GoDaddy hosting and I do have admin access.  When I installed I didn't receive any error message, even when I removed and reinstalled, I'm getting the "all clear" on the install, but still no form table.  I'm wondering if it has something to do with activating and loading from my theme.  I'll try removing and installing directly from the plug in directory and see if that clears the issue, if not I'll reply here later with my findings and any error messages I get.

Thanks!

**Comment by EvanHerman** [comment]
How are you installing the plugin via your theme? I saw in your initial post you stated "...this is an add-on through the theme", does the X Theme have some sort of method for sideloading plugins via the theme and not the standard Plugins menu? 

If so I'm wondering if the theme prevent the plugin activation hook from ever executing, which would be the reason the table never gets created in the databse.

You can check if the table actually exists or not in the databse by following the following steps:

Login to your GoDaddy account and head to the cpanel
Located phpmyadmin and open that up
Once loaded, expand the section in the left hand column to reveal the tables in your databse.
You should see somthing similar to: 

`wp_yikes_easy_mc_forms` table listed there (wp_ prefix may be different depending on your install)

If that does exist and you're getting that error than we have a larger issue at hand. If that table doesn't exist, then it could be due to the theme and I would be more than happy to do some testing for you.


Thanks,
Evan

**Comment by NicoleDelacroix** [comment]
Thank you Evan!

So in removing it via the theme (and yes, they have a side load plugin feature) I found a ghost version of 3.0 loaded.  I removed both and downloaded via the regular plugin and got the "you need to migrate" message and just like that it's fixed.  Thank you so much for the assistance, but it appears the problem was with the theme feature and not the plug in itself.  I've forwarded the issue to my theme provider so they can resolve the issue with their side load feature. 
I appreciate the help, you guys are awesome!

Thanks again!

**Comment by TheTracyL** [comment]
Yay! So glad you got this resolved.

If you're enjoying the plugin, [please consider leaving a review](https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5).

Thank you!
-Tracy

**Comment by NicoleDelacroix** [comment]
Happy to do so Tracy, I've already posted how quick and wonderful you guys
were for my issue!

Thanks again



[image: --]

Nicole Delacroix
[image: http://]about.me/nicoledelacroix
<http://about.me/nicoledelacroix?promo=email_sig>


<http://about.me/nicoledelacroix?promo=email_sig>

**Comment by EvanHerman** [comment]
Thanks again Nicole! If you run into any issues moving forward, feel free to reach back out - we're always here to help!


Evan
