### ISSUE TITLE
Redirect Not Happening

### ISSUE THREAD

**Issue by nahatjes** [yikesinc/yikes-inc-easy-mailchimp-extender#399]
I setup a landing page and used mailchimp forms.  I would like it to redirect and it just refreshes to the same page.  

www.lovechatwithnat.com/5tips is the landing page and supposed to direct to a thank you page.  

Please advise.

Natalie

**Comment by EvanHerman** [comment]
Hi Natalie,

It looks like you have some sort of JavaScript error on the page which is causing the redirect not to work properly. From what I can tell, the error is coming from the 'All In One Page Builder', specifically from the popup function. (ve_popup.js / `$popup.data is not a function`).

You may want to take a look at why that error is occuring. It may be because there is no `wp_head()` section of the template you are using, or something similar - but whatever it is, that's the reason the re-direct/entire form is not working as it properly should.

You can try toggling the option from AJAX to non-ajax on the 'Edit Form' page. You can read through the following knowledge base articles we have setup related to your issue:
https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/
https://yikesplugins.com/support/knowledge-base/submission-settings/



Evan

**Comment by nahatjes** [comment]
I already changed it to non Ajax be jade the submit button wasn't working. I will see what that plugin is...I don't think I use it. 

Natalie Hatjes

**Comment by EvanHerman** [comment]
From what I could see it looked to be this plugin: https://wordpress.org/plugins/all-in-one-wp-builder/

Evan

**Comment by EvanHerman** [comment]
If you update to the latest version of the plugin, v6.0.3.2, and set the form to not submit data via AJAX the redirect should now work. I've removed javascript dependency on non-ajax forms for the redirects.

Thanks,
Evan

**Comment by nahatjes** [comment]
Ok thank you! I will try it tonight. 

Natalie Hatjes

**Comment by TheTracyL** [comment]
Let us know how it went :-)

**Comment by EvanHerman** [comment]
Hi Natalie,

I just gave the form at the URL above a testing, and it seems that the redirect issue is now resolved. If for some reason you are still encountering issues, feel free to comment back here and re-open the issue and we can explore some additional solutions.


Thanks,
Evan
