### ISSUE TITLE
issue with the redirection to mailchimp

### ISSUE THREAD

**Issue by BabyOnMove** [yikesinc/yikes-inc-easy-mailchimp-extender#400]
Dear I observe that when I click on some links of your plugin, I am not landing on any page at all. 
The way you use the URL base of the website is wrong
http://www.archireel.be/wp-admin/%E2%80%9Chttp://www.MailChimp.com%E2%80%9D

I wonder why i obtain a concatenate between my site admin and the website to which you would like to redirect me

Can you have a look at that and correct that issue? 

Cheers, 
Julien

**Comment by EvanHerman** [comment]
Hi Julien,

I have not encountered this issue, nor has anyone else reported the issue. You may want to take a look at your .htaccess file to make sure your server is set up properly. There is no reason when linking to MailChimp why your site URL should be prepended. I'll take a second look, but from my testing - the links are fine. Who is your web host? 

Evan

**Comment by BabyOnMove** [comment]
Hi Evan,

My host is Ovh,  a hosting company from France.

I installed a mm one click package from WordPress provided by them.  So it
is possible that some parameters are not well settled.

How can I see that everything is ok with my file?

Thanks for the support,
Julien

**Comment by EvanHerman** [comment]
What link are you clicking on that's directing you to:

http://www.archireel.be/wp-admin/%E2%80%9Chttp://www.MailChimp.com%E2%80%9D

If you'd like, feel free to email me at Evan@yikesinc.com and we can discuss if you'd like me to take a closer look for you.

I believe the issue lies on your end and not necessarily with the plugin itself.


Thanks,
Evan
