### ISSUE TITLE
Only 3 Fields?

### ISSUE THREAD

**Issue by StudioH** [yikesinc/yikes-inc-easy-mailchimp-extender#422]
Hi - Just created first tester form but there are only three fields! Where/how do we add additional fields?

**Comment by TheTracyL** [comment]
Hello StudioH,

The fields are created on the MailChimp side: http://kb.mailchimp.com/lists/managing-subscribers/manage-list-and-signup-form-fields

Once they are set up there, our plugin will pull them all into your site. 

The new fields may not show up right away, because they are cached for an hour. If that happens you will need to clear the API cache. We have instructions on how to do that in our Knowledge Base: https://yikesplugins.com/support/knowledge-base/im-not-seeing-all-my-lists-on-the-drop-down-menu-when-i-go-to-make-a-new-form/

Thank you!
-Tracy
