### ISSUE TITLE
yikes-inc-easy-mailchimp-extender, interfers with my webinarsystem

### ISSUE THREAD

**Issue by baxivanos** [yikesinc/yikes-inc-easy-mailchimp-extender#425]
i after installing your plugin it interferes with my webinar system, and when i deactivate all goes back to normal view in the webinarsystem..

so can you help me to get this right ??

Andreas

**Comment by TheTracyL** [comment]
Hello Andreas,

Are you using a plugin for your webniar system? If so, can you please let us know what it is.

Thank you!
-Tracy

**Comment by baxivanos** [comment]
HI  this is  what i use 

http://www.wpwebinarsystem.com/

Best 

Andreas

**Comment by TheTracyL** [comment]
Hi Andreas,

Unfortunately that is a premium plugin we don't have access to, so we don't have a way to set up an environment with both plugins to troubleshoot.

Since you pay for their service and our plugin is free, can you put in a support ticket with them about the conflict? If they are able to provide further insight into the issue or a solution, we can do that work on our end to make a fix.

Thank you!
-Tracy

**Comment by baxivanos** [comment]
Hi I have already been speaking to them, and they tell me thay it is on your end;

 

Sending you the plugin to test and can I send you the license key to another e-mail address ??

 

I like your plugin and still want to hav your plugin on my site :) works perfectly but as you understand interferes with mu webinar system.. 

 

Best 

Andreas

**Comment by TheTracyL** [comment]
We understand.

Our email address is plugins@yikesinc.com

Thank you!
-Tracy

**Comment by baxivanos** [comment]
You will see first the problem when you setup a webinar it is in the configuration bar of the webinar,, when setting colors of the configuration details..

 

Best 

Andreas

**Comment by EvanHerman** [comment]
Hi Andreas,

I took a thorough look through the code in that plugin, and from what I can see - they are actually loading their own version of jQuery from within the plugin. This is highly frowned upon as it is guaranteed to lead you down a road of bugs. I'm actually quite surprised that they chose to handle things in this manner.

I am going to reach out to them privately via email and let them know the issue that we found in hopes that they will push out a patch for all of their users. I'm sure you're not the only one who has reported this issue to them.

On another note, I installed the plugin - and deactivated our plugin - and the webinar plugin is still throwing errors and not functioning properly. Can you confirm that when our plugin is disabled that things are working on your end? I can't seem to get the webinar plugin working at all, with our plugin installed or not.

Thanks,
Evan

**Comment by EvanHerman** [comment]
After looking through a bit more, it looks like the issue is on lines 161-171 inside of `template-metabox-generalpage.php`.

It looks like they are trying to generate a dropdown of selectable times, but they somehow wrapped the `<select>` tag in a `<script>` tag.

Changing that line to the following should resolve the issue temporarily while they look into it on their end:

```php
<select id="timeOptions">
    <?php
    echo '<option disabled="disabled" selected="selected">Select</option>';
    for ($x = 0; $x < 24; $x++) {
        for ($y = 0; $y < 60; $y+=10) {
            $time = $x . ':' . $y;
            echo "<option value='" . date('H:i', strtotime($time)) . "'>" . date('h:i A', strtotime($time)) . "</option>";
        }
    }
    ?>
</select>
```

**Comment by baxivanos** [comment]
Many thanks Evan

 

When I speak to them they just tell me that it is other plugins that has problems and noth their own. 

 

So it is much appreciated that if you can reach out to them so they correct the problems in their webcast system..

 

Your plugin is a great tool for me and our sites it is implemented on 5 sites I have and works perfectly until I installed the webinarsystem and then I got the problems..

 

So yes when I disable your plugin it seems it works OK but to be working completely I have to disable one more plugin that I use for youtube displays..

 

So yes they have serius problems with their webinar system and I will uninstall the webinar system this weekend if they don’t fix it..

 

So many thanks for your support on this

 

Best 

 

Andreas

**Comment by EvanHerman** [comment]
Hey Andreas,

No problem at all. I'm sorry the issue wasn't actually on our end - that way I would have been able to get things fixed up for you. I'm kind of surprised that they react that way. Generally, if there is an issue with our product - we are quite receptive to any feedback - especially if there is a conflict with another plugin our users are using.

I'm even more surprised that they are actually selling that product with so many bugs littered through it, and when anyone reports an issue they get very definsive.

I've left a 1 star review on their WordPress repository page - I suggest you do the same. Leaving a negative review usually gets the authors attention, especially if that is there main source of marketing. Seeing as the issue is quite large and WILL cause issues with the majority of people who use it, I think a 1 star review is warranted and fair.

https://wordpress.org/support/view/plugin-reviews/wp-webinarsystem

Hopefully they get things fixed up for you, since you are a paying customer with them. I would at least expect them to go through and update how (and what) scripts they are using.

Thanks,
Evan
