### ISSUE TITLE
subscription does not work

### ISSUE THREAD

**Issue by margiela** [yikesinc/yikes-inc-easy-mailchimp-extender#441]
subscription does not work. the user does not receive any email......

my web site is www.otveyewear.com

**Comment by TheTracyL** [comment]
Hello Margiela,

Where is the form, exactly?

Thank you!
-Tracy

**Comment by margiela** [comment]
hi tracy
http://www.otveyewear.com/newsletter/

**Comment by TheTracyL** [comment]
Hi Margiela,

When we inspect that page using the console there are a lot of errors coming from `embed.js` which could be used by the theme or another plugin.

Can you please try turning AJAX off for the form (instructions here: https://yikesplugins.com/support/knowledge-base/submission-settings/) and give it another try?

Let me know when you've done that, because I'd like to test it as well.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Margiela,

Just checking in, did you try turning Ajax off?

Let us know.

Thank you!
-Tracy

**Comment by margiela** [comment]
Yes Now it's perfect
Thank you

Micol Crugnola
Tel. 3481521806
Skype: micool01

**Comment by TheTracyL** [comment]
Awesome! That's great news.

We're glad we were able to help.

Thank you!
-Tracy
