### ISSUE TITLE
White screen when entering API Key 

### ISSUE THREAD

**Issue by srconrad** [yikesinc/yikes-inc-easy-mailchimp-extender#443]
I downloaded the plugin  running the latest version of WordPress Debian 6 server and when I try to enter the API Key  in the setup of the plugin it gives me a white screen it seems to be loading /wp-admin/options.php I tried changing the rights to that file. I also changed the right to the folder it is in that did not help. I uninstalled the plugin and re-installed the plugin.

When I go to mailchimp site and look at the log in I see it trying in the log. I tried three API Keys. Still no luck.

Any help would be great.
Thanks Stephen

**Comment by EvanHerman** [comment]
Hi Stephen,

What is the URL of the page when you hit that white screen? Something may not be redirecting properly after saving the API key. I'm not entirely sure why this would be happening, but if you'd like to email us we can take a look at your site personally - since we are unable to reproduce the issue on our end. https://yikesplugins.com/about/contact/

When you save the settings, the site options table gets updated in the database so I don't believe file permissions are to blame here.

Evan

**Comment by srconrad** [comment]
Email sent as requested thanks.
Take care 
Stephen

**Comment by srconrad** [comment]
Evan,

I believe the problem might be it can not write to the database the database user is set as local host but the request is coming from in my case ve9sc.com not local host. I might be total off base I am just learning as I go. I looked at the option table I see nothing in yikes api or other field that I believe are related.
When I setup the Wordpress I set it as local host for the connect to MySQL database. This is just my theory you know more about this then me. Is there a way now to fix this I tried changing the world config but I broke the database connection I used root with root password and ve9sc.com as host I also tried 12.168.0.235 the IP of the PC on my lan 

Take care

**Comment by EvanHerman** [comment]
Are you able to see what's inside of the database? Can you check if a table exists, called wp_yikes_easy_mc_forms (wp_ may be some other value).

If that table does not exist, that is most likely the problem here.


Thanks,
Evan

**Comment by srconrad** [comment]
Yes there is a table there is 18 eighteen columns in the table

**Comment by srconrad** [comment]
It seems like it can not write to the table. 

Sent from my iPad

**Comment by srconrad** [comment]
Ok Evan I did something I had an old laptop I just installed Debian 7 then pup MySQL Apache  then Wordpress them your plugin.

Guess what same white page I have other php scripts for my genealogy page that write to it tables etc. 

When I setup the laptop I gave all files and folders 777 to rule out permissions problems.
I also used 127.0.0.1 instead of local host to see it that would make a difference. 

I don't know what else I need to do to make this work, is this the first time this has been reported?

**Comment by EvanHerman** [comment]
Hi srconrad,

This is the first time the issue has been reported on our end. We did have one other previous user report something similar, but they were running a Windows IIS server, and we weren't able to reproduce the issue on our end.

I would need to replicate your identical setup (server and all) to reproduce the issue on my end, and I don't have a version of Debian setup on any of my machines.

Evan

**Comment by srconrad** [comment]
Evan,

I believe you have given up I understand, I being the only person with this  but I believe your plugin with not work on Debian for some reason. Today at work a IT staff member who works for me started from scratch I did not direct him so not to influence it.

I gave him the following requirements: 
Newest version of software to be installed
Debian
MySQL
PHP
Wordpress
Your plugin and only your plugin
New account Mailchimp new API key
All went well until the white screen for the API 

He asked me to ask you if you could provide a SQL script to install the API key to see if that would work.  Or is the Key stored in a file if so can you provide this info. The tables are created but are empty. I now have two techs looking at it if they come up with a solution I will advise.
Can you tell me what Linux versions it has been tested we could try that to see if we can get it to work. 

Thanks

**Comment by EvanHerman** [comment]
It's not that I have given up - I just cannot reproduce the issue on my end, and unfortunately do not have access to your servers/ftp to poke around and see what may be wrong myself. Without actually having access to the issue, it's near impossible for me to know what the issue is - and to come up with a solution for you.

As for updating your API key, you can try manually entering the API key using build in WordPress functions:

`update_option( 'yikes-mc-api-key' , 'API KEY HERE' );`

In regards of testing, I am no sys-admin so I am not too familiar with OS's and their nuances - but I currently have things installed and running on a Linux CentOS server. We also have things actively running on a number of our client sites on WP Engine ( Apache/Nginx? ).

Are the Debian sites you are setting up setup on a live server that I can access? Or is everything localhost installs? 

I am actually quite curios as to the problem, and if I had access to the servers, would be more than happy to dig in for you.


Thanks ,
Evan

**Comment by EvanHerman** [comment]
What version of PHP is your site currently running? I have another user who I am working directly with to help resolve a similar issues. He is receiving a white screen on the edit form page.

I believe that his issue is due to an outdated version of PHP (5.3) whereas WordPress is recommended to be running at 5.6 or later (https://wordpress.org/about/requirements/)

Thanks,
Evan

**Comment by srconrad** [comment]
I had 5.4.45-0+deb7u2 just upgraded to 5.6.18-1~dotdeb+7.1

The server that was build today It has all the latest of all software but the web server I am trying to setup was not up to date but now is.

Same problem white screen


Sent from my iPad

**Comment by EvanHerman** [comment]
Ok, thanks for reporting that. I'll let you know the outcome of the other users issue, since I have access to the back end of their site to view and test the issue.


Evan

**Comment by srconrad** [comment]
Evan,

I get it working
sudo apt-get install curl
Then Restart Apache by typing sudo service apache2 restart
Then Install PHP5 CURL by typing sudo apt-get install php5-curl
Then Restart Apache by typing sudo service apache2 restart
Your plugin seems to need curl install, once I installed curl it worked tried it on two box and it fixed both.
I was reading about Wordpress White screen problems and the posts stated to adding curl fixed most, so I gave it a try and it worked.
Thanks for the help and support, if others have the same problem it may help them.
Take care
Stephen

**Comment by EvanHerman** [comment]
Hey Stephen,

Wow that's awesome - thanks for posting the solution here. I'm sure that'll come in handy for someone in future. I should have thought of the CURL issue, as the [MailChimp API PHP](https://bitbucket.org/mailchimp/mailchimp-api-php/src/03ae0dba64d1a902fb4d76004ef12c8391ededc8/src/Mailchimp.php?at=master&fileviewer=file-view-default) wrapper we have included in the plugin makes the communication via CURL.

I'm glad you were able to get things resolved, and I will pass along this information to the other user who is having issues.


Thanks!
Evan
