### ISSUE TITLE
Warning: sprintf(): Too few arguments 

### ISSUE THREAD

**Issue by Bulbow** [yikesinc/yikes-inc-easy-mailchimp-extender#447]
Dear Yikes,

In my website your plugin show me a warning message...

Warning: sprintf(): Too few arguments in C:\inetpub\wwwroot\ban\wp-content\plugins\yikes-inc-easy-mailchimp-extender\admin\class-yikes-inc-easy-mailchimp-extender-admin.php on line 505

Please what's this?

![error_arguments_](https://cloud.githubusercontent.com/assets/17203872/13120901/02fac78c-d597-11e5-9743-0f6ebfdcc1c5.JPG)

Best regards,
Marcos

**Comment by EvanHerman** [comment]
Hey Bulbow,

It sounds like the notice is looking for your first name from the user profile page, but you haven't saved it yet. We do have a fallback in place so that when there is no first name found, it excludes the name so I'm not sure why you would be getting the error message.

Can you try updating your details on the User Profile page. (Users > Your Profile).


Thanks,
Evan

**Comment by Bulbow** [comment]
Evan your answer it’s perfect! I update my profile and the message go out!

 

Thanks!!

[],

Marcos

 

De: Evan Herman [mailto:notifications@github.com] 
Enviada em: quarta-feira, 17 de fevereiro de 2016 17:08
Para: yikesinc/yikes-inc-easy-mailchimp-extender <yikes-inc-easy-mailchimp-extender@noreply.github.com>
Cc: Bulbow <marcos.bulbow@gmail.com>
Assunto: Re: [yikes-inc-easy-mailchimp-extender] Warning: sprintf(): Too few arguments (#447)

 

Hey Bulbow,

It sounds like the notice is looking for your first name from the user profile page, but you haven't saved it yet. We do have a fallback in place so that when there is no first name found, it excludes the name so I'm not sure why you would be getting the error message.

Can you try updating your details on the User Profile page. (Users > Your Profile).

Thanks,
Evan

**Comment by EvanHerman** [comment]
Awesome,

I'm glad it was a nice and simple fix. I will keep this in mind when I begin working on our next update. I appreciate you taking the time to report the issue here.

If you continue to use the plugin and find it useful - we would really appreciate a positive review and to hear any positive things you have to say about the plugin:

https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

Thanks again Marcos,
Have a great rest of your day!
Evan
