### ISSUE TITLE
Signing up a second time with the same email address

### ISSUE THREAD

**Issue by GrahamBruno** [yikesinc/yikes-inc-easy-mailchimp-extender#460]
I am finding that when users signs up with an same email address that is already on file in the system they are receive the same message as new subscribers "Thank you for subscribing! Check your email for the confirmation message." 

Their entry in the mailchimp list is immediately updated in the list without any form of confirmation message being sent to authorise the change. "Send a final welcome email" is enabled in mailchimp itself  and double opt-in is enabled in the plugin settings.

When email addresses sign up for the first time they are receiving the final welcome message as expected to authorise their initial inclusion on the list. 

Is there a setting for users to be notified when someone fills in the sign-up form with new details for a given email address and for the holder of that email address to be able to authorise the change being made (or at the least be advised of it).

Many thanks in advance for your time,

Graham

**Comment by EvanHerman** [comment]
Hi Grahma,

Yes there is a way for you to set whether to update existing subscriber or not. Take a look at the following knowledge base article:
https://yikesplugins.com/support/knowledge-base/opt-in-settings/

At this time there is no way to be notified when someone updates their credentials. This would require incorporating webhooks via MailChimp, and it's not something we have built out right now.

In a previous version we included two factor authentication, so users information is not updated maliciously by a third party user.


Evan

**Comment by WaseemMarwas** [comment]
Hi,

My objective is to let people sign up with one email address a second time free of hassle.

If someone attempts to do that, they get a message saying they are already signed up and should update their profile. But even if they do so, they are not redirected to the assigned site.

In Easy Forms, the "Update Existing Subscriber" option states: "Display an update link when a user is already subscribed to the list, allowing them to generate an email where they can update their subscribtion info - instead of displaying a "user already subscribed" message."

What I want, however, is that users are able to sign up a second time while their profile is updated automatically. - It used to be possible in another version (I have Version 6.0.5).

Thanks & Regards,
Waseem

**Comment by EvanHerman** [comment]
Hi Waseem,

This was possible but was considered a security issue by a number of our users. We've since updated the plugin to utilize a two factor authentication workflow.

Otherwise a user could update any other users credentials.


Thanks,
Evan

**Comment by garrymansfield** [comment]
hello
we use the plugin to add groups of interests for campaigns for users in mailchimp. since the upgrades I cannot upgrade group information for an existing user. you have provided some code above that you seem to indicate will fix the problem... but i am not a programmer and it is not clear what i have to do with this.can you help? 

I do not want a user to get an email other than the document they requested in the form.

thanks
Garry

**Comment by TheTracyL** [comment]
Hi Garry,

This code would go in your theme's `functions.php` file.

If are not comfortable editing the functions.php file of your active theme, you can use this plugin https://wordpress.org/plugins/my-custom-functions/

Let us know if you need further help.

Thank you!
-Tracy

**Comment by garrymansfield** [comment]
Thanks Tracy,
this is working well now, though i needed to re  build the campaigns on the forms. 

Another quick question (I will look for another thread too) - Is there a way to pre-populate content for known users? ie when i fill in one form my name and email are automatically filled in and i just need to submit?

thanks 
Garry

**Comment by TheTracyL** [comment]
No, we have implemented email verification for updating profiles. Allowing profile updates without email verification would be a security issue.
