### ISSUE TITLE
Form problem | combine mailchimp & file upload plugin

### ISSUE THREAD

**Issue by MichaelGradH** [yikesinc/yikes-inc-easy-mailchimp-extender#476]
Hi everyone!

site adress: http://www.kmu-jobs.com/up-out/

I am looking for a way to include a file upload plugin - listed as CV Upload above the mailchimp form on my site - within my mailchimp registration process. What I need is to include the external "upload file button"  process - which means the file is getting uploaded after clicking - as soon as someone klicks the mailchimp "PROCEED" Sign Up button on the bottom of my mailchimp form. So best case I can remove the "upload file" button from my site and the external upload is combined with the registration for my mailchimp list.

The file upload plugIn I am using right now is called "Wordpress File Upload".

If there is a better way to include the file upload already within mailchimp process or to use a different more useful plugIn I would be also really grateful for some advice.

Please help me out how to solve this issue.

Thank you very much in advance for your support!

Michael

**Comment by TheTracyL** [comment]
Hi Michael.

A file upload is not a field that MailChimp allows you to add to a form, so out-of-the box you can't incorporate a file upload field with our plugin.

You could add the file upload field to a page the user gets redirected to after they submit the form an via the UI you can make it look like that is Step 2 of the process. Hopefully the file upload allows you to create a custom success page or message after they complete the upload. The downside to this option is the user does not need to do the upload after the form is submitted, and you will get some submissions with no file.

I do not know if there is a way for our submit button to hook into another plugin to submit the file along with our form. That is a question for Evan.

Thank you!
-Tracy

**Comment by MichaelGradH** [comment]
Hi Tracy,

thanks a lot for your quick response!

Ok I hope Evan can help me out to solve this issue because thats excatly what I need.

Best wishes 

Michael

**Comment by MichaelGradH** [comment]
Hi Evan,
Hi Tracy,

any updates on this problem?

Thank you very much again for your support.

Michael

**Comment by EvanHerman** [comment]
Hi Michael,

You best option, and only option using our plugin, is to extend the plugin using the various hooks and filters we have provided within the plugin, to add a new file upload field to your form. This would involve writing custom code on your end to handle both the file upload, and the data that gets sent to mailchimp.

Off the top of my head, you'll want to use the `[yikes-mailchimp-additional-form-fields](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/plugin_core/public/partials/shortcodes/process_form_shortcode.php#L1113)` hook to add additional form fields to your form.

This is the section your going to want add your new field, include the javascript to initialize the file upload and to handle the file being uploaded.

Once you have the field setup, you're going to need to do something with the new data.
 
You'll want to hook into the `[yikes-mailchimp-before-submission](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/plugin_core/public/partials/shortcodes/process/process_form_submission_ajax.php#L126)` action hook we have setup, to do something with the new file that was uploaded by the user.  I'm not sure what you're doing right now with the file, but you'll need to write a function to handle things in a similar way.

Finally, you'll want to remove the new file/field uploaded via the form from the MailChimp payload data (API data being sent over to MailChimp).

You can alter the data being submitted to Mailchimp using the filter `yikes-mailchimp-before-submission`. You'l want to remove the file upload field from the array of data getting sent to MailChimp since it will not know how to handle it.

Since there are so many steps to what you are asking, and heavily reliant on how you have things setup - I am not able to provide code but could at least point you in the right direction.


Thanks!
Evan
