### ISSUE TITLE
Español translate

### ISSUE THREAD

**Issue by reytercero** [yikesinc/yikes-inc-easy-mailchimp-extender#511]
I cant translate 2 things in my in ajax form.

1. The validation error message in email field :
******Please fill out this field******** 

2. The email registered message:
*************reytercero@gmail.com is already subscribed to the list. **************

you can see my forms in sidebar and footer of my site: http://vutik.com/empresas/

so many tks.

**Comment by EvanHerman** [comment]
Hi Reytercero,

The 'Please fill out this field' is generated by the browser, and not something that can be handled by the plugin itself. 

Similar to the first issue, the email registered message is generated by MailChimp itself, and not handled by the plugin. The translation would need to come from them - since when the form is submitted the email is validated on their end and an appropriate message is returned.

We are currently working on/exploring additional options for translations within the plugin.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hello I am going to close out this ticket, because we added the ability to translate the profile validation message to future features list.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello,

This is going to be included in the update that comes out today: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/537

Thank you!
-Tracy
