### ISSUE TITLE
Redirect on Submission not working

### ISSUE THREAD

**Issue by rachelreally** [yikesinc/yikes-inc-easy-mailchimp-extender#539]
My forms are set to redirect to a Thank You webpage on my site, but the redirect no longer works. I've tried change the Page/Post to redirect to, installed the latest update, and even uninstalled then reinstalled the plugin. The function is still failing to redirect. Can you assist please? I saw another issue of the same type recorded on the Wordpress support log.

![image](https://cloud.githubusercontent.com/assets/20422265/16788406/fd3abcd8-4861-11e6-9276-c055070d24ee.png)

**Comment by TheTracyL** [comment]
Hello

I just tested a redirect on my test site and it worked for me with the latest version of the plugin. 

Can you please provide a link to your form so I can test?

Do you know the exact date it stopped working?

Thank you!
-Tracy

**Comment by rachelreally** [comment]
Hi, Tracy - thanks for your quick response!

Here are the two webpages on my site where I readded forms after my
reinstall of the plugin:
http://really.social/be-our-guest/
http://really.social/newsletter/

Neither form is redirecting to this page: http://really.social/thank-you/

Any help you can offer is very appreciated. Thanks again!

**Comment by TheTracyL** [comment]
Did they work at one time? When did you notice it stopped working?

**Comment by rachelreally** [comment]
Yep, they worked when I first installed the plugin, plus I had successful
signups complete. I only noticed it wasn't working this week when I tried
to set up a lead capture Web page to redirect to a downloadable infographic.

**Comment by EvanHerman** [comment]
The redirects don't work because you have javascript errors ony our page. Unfortunately, we can't tell where it's coming from - or how to fix it - since it's not coming from our plugin.

You can try switching themes, or disabling other plugins to help find the cause - but without access to your site we can't tell you any additional information.

For additional information, feel free to read through the following articles:
https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

Since there is a .js error on the page, your AJAX forms aren't going to work properly at all. Meaning no subscriber info is going to process through to MailChimp.

At the moment, without clearing up the .js errors, the only way to work around the issue is to set your forms to not use AJAX, but instead be a standard form that refreshes the page after the form has been submitted.

Thanks,
Evan

**Comment by EvanHerman** [comment]
![Example](https://cldup.com/86vWSOn_6n.jpg)

**Comment by rachelreally** [comment]
Thank you so much! I'll make the changes and see if that helps. I'll let
you know. I really appreciate you looking into it.

**Comment by rachelreally** [comment]
That worked! I so appreciate your help. :)

On Wed, Jul 13, 2016 at 12:53 PM, Rachel Moore <rachelreallysocial@gmail.com

**Comment by TheTracyL** [comment]
Awesome! I am so glad we were able to resolve your issue.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
