### ISSUE TITLE
An Icon in the Opt-in Form Submit Button Disappears after Submitting

### ISSUE THREAD

**Issue by Pixelous** [yikesinc/yikes-inc-easy-mailchimp-extender#568]
Hi,

an icon in the opt-in form submit button disappears after submitting https://yikesplugins.com/support/knowledge-base/add-an-icon-to-the-optin-form-submit-button/

Can you please fix it?

**Comment by TheTracyL** [comment]
Hello,

May I please have a link to your form so I can see what you are referring to.

Thank you!
-Tracy

**Comment by Pixelous** [comment]
@TheTracyL here is the demo URL http://demo.themeuniverse.net/baikal/demo-17/

See the form in the footer.

After clicking submit button it disappears, preloader image appears, then preloader image disappears and  the icon in the submit button does not appear any more.

**Comment by EvanHerman** [comment]
Hi @Pixelous 

It looks like this is happening because when the form is submitted, our JavaScript is retreiving the current .text() of the button, and the arrow is being appended to the button text using html.

`.text()` doesn't grab the HTML included, just the text. We will need to update this to `.html()` so the icon (or any other HTML added to the button) is properly added back to the button.

Line:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/js/yikes-mc-ajax-forms.js#L17

We will have to update this and get it pushed out in the next update.

Thank you for catching this and bringing it to our attention!


Evan

**Comment by Pixelous** [comment]
@EvanHerman  thanks,

can you also add:

1. some class to the form while loading.

2. instead of replacing the button text with the loading image add the loading image above the button text? You can still hide the text via CSS in case of adding class to the form while loading.

?

**Comment by Pixelous** [comment]
@EvanHerman you will need to replace `text` on line83 also

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/js/yikes-mc-ajax-forms.js#L83

**Comment by kpu23** [comment]
Hi @Pixelous,

Sorry it took us this long to recognize you're request. I am currently prepping a new release for the plugin and it will include (1) wrapping the button text in a span (with the class `yikes-mailchimp-submit-button-span-text`), (2) the button text will no longer be removed, it will be hidden, but the loading dots gif is still appended/removed and (3) a class to the actual form element while it's being submitted (is this what you mean by loading?)

**Comment by Pixelous** [comment]
Hi @kpu23 

sorry for the late reply.

1. Thanks.

2. Thanks.

3. Thanks. Yes.
