### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by frateaubets** [yikesinc/yikes-inc-easy-mailchimp-extender#616]
Hi,
I've been testing the form integration with Mailchimp. Our website it is translated to EN / ES but the form always appears in the last language that we edit the form. I already checked your translation guide https://yikesplugins.com/the-ultimate-guide-to-translating-mailchimp-forms-on-wordpress-sites/ but what I'd like it is a form in the user language, not only english or only spanish. Also for the custom messages. I've been testing also the wp [:en][:es][:] but nothing.

Thank you very much and congrats for your great work.

Frate

**Comment by TheTracyL** [comment]
Hello Frate,

What method are you using to offer your site in Multiple Languages?

Thank you!
-Tracy

**Comment by frateaubets** [comment]
Hi Tracy,
Qtranslate-X

Tnx.

El 13/12/2016, a les 17:49, Tracy Levesque <notifications@github.com> va escriure:

**Comment by TheTracyL** [comment]
Thank you for that info. The issue is probably that our plugin is not compatible with Qtranslate-X. We've had our plugin reviewed by the folks at WPML and there are some steps we need to take to make our plugin compatible with that plugin, so I imagine we'd have to do some work to make it work with this one.

Is there any way to serve up a separate form depending on the language the user has chosen?

I am very sorry it's not working of the box with Qtranslate-X.

Thank you.
-Tracy

**Comment by frateaubets** [comment]
Hi Tracy,
I'll try it, probably it is the best solution. We use only 2 forms, so we
will have 4, each on connected with their own list in MC.

Thanks!



El dt., 13 des. 2016 a les 18:17, Tracy Levesque (<notifications@github.com>)
va escriure:

**Comment by TheTracyL** [comment]
You're welcome!

Have a good day :-)
-Tracy
