### ISSUE TITLE
Mail chimp Forms Customiser

### ISSUE THREAD

**Issue by spandrews13** [yikesinc/yikes-inc-easy-mailchimp-extender#617]
Hi,

I have just installed the forms customiser add on and have got as far as trying to customise my new form but and I click on the button here:

https://snag.gy/oI6EzQ.jpg

It goes to this page and say that its loading. But nothing happens. I have waited up to 10 minutes before closing the tab:

https://snag.gy/KHWAbm.jpg

Thanks
Regards
Simon

**Comment by kpu23** [comment]
Hi Simon,

What version of WordPress are you using? Have you updated to the 4.7?

Kevin.

**Comment by spandrews13** [comment]
Hi Kevin,

Thanks for your reply. yes I am using version 4.7

Thanks
Simon

**Comment by kpu23** [comment]
We should check for JavaScript errors in the console. Do you know how to access your browser's developer tools / console?

**Comment by spandrews13** [comment]
Thanks - here are the details from the console (screen shot and copy/paste of text)

https://snag.gy/3L6OGj.jpg

load-scripts.php:9 JQMIGRATE: Migrate is installed, version 1.4.1
form-submit-button-width-ui-slider-field.js?ver=all:6 100
load-scripts.php:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.send @ load-scripts.php:4
about:blank:1 Refused to display 'http://staging2.tripsavvy.co.uk/?customize_changeset_uuid=06bb81b5-8158-487…6939fb197a&customize_theme=Newspaper&customize_messenger_channel=preview-0' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://tripsavvy.co.uk".
VM2550:1 Deprecated TinyMCE API call: <target>.onChange.add(..)

**Comment by kpu23** [comment]
Hi Simon,

Thanks for the detailed output. The "Refused to display..." error is breaking the customizer. I'm reading up on the error now. Have you ever used WordPress' built-in customizer for anything? It seems like your host is disallowing iFrames to your site, which would make the WordPress built-in customizer break also. Can you check if that's the case?

Thanks,
Kevin.

**Comment by spandrews13** [comment]
Hi Kevin,

This was the response form the hosts, Siteground. I have followed this instructions and reinstalled the plug ins but the problem remains the same:

Hello Simon,

I can again confirm that the following rule:

Code:
Header set X-Frame-Options: SAMEORIGIN


has been properly set in your .htaccess file.

However, in this case I would recommend you to try re-installing the following plugin on your staging website or to discuss the matter further with a skilled Wordpress developer:

Code:
yikes-inc-easy-mailchimp-form-customizer-extension


Best Regards,

Vladimir Trandev
Senior Technical Support

**Comment by kpu23** [comment]
Hi Simon,

Are you seeing the same `...Content Security Policy directive: frame-ancestors...` error as before? If so, then I think the problem is still with the host (and I don't mean to keep pushing you back to them!) The X-Frame-Options are a _different_ HTTP header than the Content-Security-Policy header, and it is possible that these two could conflict (where one is saying 'allow' while the other 'deny'). I am not an expert with these, but if you're still receiving the Content Security Policy error then I think you need to go back to your host and ask them to set the Content-Security-Policy: frame-ancestors response header (more info [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)). There is nothing in the code that would trigger that error. 

Were you able to confirm that the same error occurs for WordPress' built-in customizer?

Sorry for the trouble,
Kevin.

**Comment by kpu23** [comment]
Hello again Simon,

I've been reading up on the Content-Security-Policy. I think that the issue might be that you're on a staging site. In the screenshot you sent me you're working from a `http://staging2...` domain. Do you have an `https` domain? It may be that your host has set the Content-Security-Policy to `https` and therefore you can't use iFrames on your staging site. (you could test this by trying to use WordPress' built-in customizer on your `https` site). 

Also, I believe the exact header you would like to set is `Content-Security-Policy: frame-ancestors 'self';` as this would most align with the similar `X-Frame-Options: SAMEORIGIN` you have.

Again, I am not an expert with HTTP headers, so your host should be the definitive source, but I feel bad telling users to go and bug someone else!

Cheers,
Kevin.
