### ISSUE TITLE
No Mailing Lists

### ISSUE THREAD

**Issue by inkastour** [yikesinc/yikes-inc-easy-mailchimp-extender#669]
Ever since the new update from yesterday 22, February, 2017 all of my Mailing Lists have been lost in the Plugin. I can not create any new Forms or use the old once. I have tried deleting the Cache settings, I have deleted the plugin and installed it again. I have used a different API and I have waited overnight to see if I would be able to see the lists in the morning.

I am out of options. I have just invested in the customize plugin so I am a little sad that it does not work.
Please help!

**Comment by kpu23** [comment]
Hello @inkastour,

I'm sorry about that! The plugin update was pretty minimal and should not have had an affect on your mailing lists. It sounds to me like communication between your server and MailChimp is being blocked. Are you able to access any MailChimp-related data? What happens when you go to the "Account" page? Is that page also blank? 

We've seen the issue of IP addresses being blocked by MailChimp popping up a lot lately, so it might be that. If it is, you'll need to contact your hosting company and/or MailChimp.

Let me know if you have any more details,
Kevin.

**Comment by abswebbr** [comment]
I am having the exact same problem and I have no idea how to fix that... :-(

**Comment by abswebbr** [comment]
I have cleared the API Cache and it Worked!

**Comment by kpu23** [comment]
Sounds good @abswebbr!

@inkastour - How's it going? Any update?

**Comment by rolfkleef** [comment]
I appear to have the same issue, but clearing the API cache or adding a new API key doesn't work.

The Mailchimp Account page in Wordpress only shows "Member since 1 January 1970", the other fields are empty. The front-end error message is "You're already subscribed. To update your MailChimp profile, please click to send yourself an update link".

It does work from my laptop, so an IP block seems the most logical at this point. Also, the API keys page at MailChimp shows API log messages from my laptop, but none from the server.

Is there a way to diagnose why MailChimp blocks an IP address? Probably because some spam attack via Wordpress or the EasyForms plugin?

**Comment by kpu23** [comment]
Hi @rolfkleef,

I agree - this sounds like an IP block.

The most likely reason for this is that many hosting companies assign your server an IP from a pool of IP addresses. These IP addresses are used by other clients as well, so you could be sharing an IP address with another user. If any of the users sharing that IP have had what MailChimp considers "Malicious Activity" they will flag your server and block all traffic.

The only way to get yourself unblocked (and learn why you were blocked originally) is to contact MailChimp (or your hosting company). 

So - contact them. If for whatever reason that's not the issue, let us know and we can dig deeper.

Cheers,
Kevin.

**Comment by rolfkleef** [comment]
Thanks Kevin! I'm trying to find out how to contact MailChimp, but it looks like I first need to become a paying subscriber... Will check with my hosting provider tomorrow morning if they can move the site to another IP.

**Comment by kpu23** [comment]
Check this article: http://kb.mailchimp.com/delivery/spam-filters/how-blacklists-work

It includes a way to check if your IP is being blacklisted.

**Comment by rolfkleef** [comment]
Ok, my final argument to move hosting provider... Via http://www.tcpiputils.com/domain-neighbors "Found 792 domains hosted on IP address x.x.x.x"... I was monitoring for appearance on Spamhaus lists already, but this is unmanageable... ;-)

**Comment by kpu23** [comment]
Haha! That's a lot of domains sharing an IP; I'm sorry about that! Best of luck with your switch.
