### ISSUE TITLE
403 Forbidden Error when customizing forms.

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#680]
Hi again,
I forgot to ask before but I recently got the form customizer plugin. Whenever I want to customize the form I get a console error: "NetworkError: 403 Forbidden - http://newsite.myclientschedule.com/wp/?customize_changeset_uuid=54d0f02b-fde6-47dd-b285-2e8aff55be88&customize_theme=Divi&customize_messenger_channel=preview-0"

This only happens for one particular form as the other ones work for some reason. The plugin I am using is the 	"Easy Forms for MailChimp Form Customizer Extension by YIKES"

**Comment by kpu23** [comment]
Hi @Lir2303,

Because you purchased one of our plugins, you can use our premium support board: https://yikesinc.freshdesk.com/support/login. Could you please post there? The conversation will be private, and I think we'll need that privacy to debug this issue.

Cheers,
Kevin.

P.S. Thanks for supporting us and purchasing a plugin!!!

**Comment by Lir2303** [comment]
Perfect, thanks.

**Comment by Lir2303** [comment]
Is this using the same login that I used to purchase the plugin

**Comment by kpu23** [comment]
Sorry - I gave you the wrong instructions. Don't use that URL. Go to the "Support" section of the Easy Forms plugin and you'll see a form to submit a ticket. That's how you do it. My apologies.

**Comment by Lir2303** [comment]
Yeah, no problem. I just sent the email.
