### ISSUE TITLE
How to make a dropdown required?

### ISSUE THREAD

**Issue by jasonhildebrand** [yikesinc/yikes-inc-easy-mailchimp-extender#736]
It's not clear to me how to make a dropdown field required.  In my use case I have a list of provinces.  

Since the form displays the first choice by default, I created a "Please select..." option in mailchimp.  I did this because that is better UX than defaulting to an actual province (which the user may simply accept without updating the field).  I set "Default Selection" to this value.

But I want to require the user to select a different option.  I tried "Field Required" but it made no difference. For my use case, "Field Required" should mean that the user must change the field to a different value than the default selection.  Would this make sense generally? 

I can work on a PR if this approach would be acceptable.

**Comment by kpu23** [comment]
Hi @jasonhildebrand,

I understand your dilemma. 

The way it currently works is that "Field Required" means we add HTML's `required` attribute to the field. The problem is that your "Please select..." option has a value of "Please select..." rather than an empty value. If it had an empty value, then the required field logic would work. 

I think the best way to accomplish what you're trying to do is to add a way to remove the "value" from a dropdown option. This could be done in the form builder or through filters. I think adding a filter for each dropdown choice's name and value would be the way to go. 

What do you think?

Let me know,
Kevin.

**Comment by jasonhildebrand** [comment]
Yes, that approach would work.  However I have a related requirement in my project that I need this dropdown field to be required (or not required), based on what option the user selects in a different field.

What I have done is make a small modification to `public/js/yikes-mc-ajax-forms.js` to invoke a custom validator function `yikes_mailchimp_custom_validation` (if it exists), passing the current form.  This validator can take necessary actions and returns true/false to indicate whether validation is successful.

This gives me the flexibility to meet my requirements with only a small mod to your project.  I can submit a PR if you are interested (but I understand if you don't want to incorporate this change).

**Comment by kpu23** [comment]
That's the best way to do it. 

If WordPress had an infrastructure for JavaScript hooks/filters, we could incorporate this properly. Without that infrastructure, I think we'll leave the plugin as it is for now.

**Comment by jasonhildebrand** [comment]
OK, sounds good.
