### ISSUE TITLE
Unable to Edit Forms

### ISSUE THREAD

**Issue by VictoriaLV** [yikesinc/yikes-inc-easy-mailchimp-extender#859]
Hi, 

The forms created in the MailChimp plugin have the "Download Now" button off center on our webpage.  When I go to the plugin and select the form and click edit,  I get the message below and I am not able to edit it.  Please advise on how I can go back to be able to edit the forms.  This message is coming up with all the forms built in the plugin. The plugin has been updated to the most recent version available.

![image](https://user-images.githubusercontent.com/38795418/94613784-2169ab80-0273-11eb-989e-539fc0dac0e0.png)

**Comment by freddiemixell** [comment]
@VictoriaLV 

For plugin support please refer to our support forums: https://wordpress.org/support/plugin/yikes-inc-easy-mailchimp-extender/

I'm going to keep this open because I'm not sure if you have a developer related question. 

Can you check your browsers Javascript console? Do you see any errors? Some users with this same issue resolved by adding this plugin to their site:
https://wordpress.org/plugins/enable-jquery-migrate-helper/

Cheers,
Freddie
